
snd-asoc-dma-v12-objs 	:= asoc-v12/asoc-dma-v12.o
snd-asoc-aic-v12-objs 	:= asoc-v12/asoc-aic-v12.o
snd-asoc-i2s-v12-objs 	:= asoc-v12/asoc-i2s-v12.o
snd-asoc-pcm-v12-objs 	:= asoc-v12/asoc-pcm-v12.o
snd-asoc-spdif-v12-objs := asoc-v12/asoc-spdif-v12.o

snd-asoc-dma-v13-objs 	:= asoc-v13/asoc-dma-v13.o
snd-asoc-i2s-v13-objs 	:= asoc-v13/asoc-i2s-v13.o
snd-asoc-pcm-v13-objs 	:= asoc-v13/asoc-pcm-v13.o
snd-asoc-spdif-v13-objs := asoc-v13/asoc-spdif-v13.o
snd-asoc-dmic-v13-objs := asoc-v13/asoc-dmic-v13.o

snd-asoc-icdc-d1-objs := codec/icdc_d1.o
snd-asoc-icdc-d2-objs := codec/icdc_d2.o
snd-asoc-icdc-d3-objs := codec/icdc_d3.o
snd-asoc-excodec-npca110p-objs := codec/npca110p.o
snd-asoc-excodec-akm4951-objs := codec/akm4951.o
snd-asoc-pcm-dump-objs := codec/pcm_dump.o
snd-asoc-spdif-dump-objs := codec/spdif_dump.o
snd-asoc-dmic-dump-objs := codec/dmic_dump.o

obj-$(CONFIG_SND_ASOC_DMA_V12) += snd-asoc-dma-v12.o
obj-$(CONFIG_SND_ASOC_DMA_V13) += snd-asoc-dma-v13.o
obj-$(CONFIG_SND_ASOC_JZ_AIC_V12) += snd-asoc-aic-v12.o
obj-$(CONFIG_SND_ASOC_JZ_AIC_I2S_V12) += snd-asoc-i2s-v12.o
obj-$(CONFIG_SND_ASOC_JZ_AIC_I2S_V13) += snd-asoc-i2s-v13.o

obj-$(CONFIG_SND_ASOC_JZ_ICDC_D1) += snd-asoc-icdc-d1.o
obj-$(CONFIG_SND_ASOC_JZ_ICDC_D2) += snd-asoc-icdc-d2.o
obj-$(CONFIG_SND_ASOC_JZ_ICDC_D3) += snd-asoc-icdc-d3.o
obj-$(CONFIG_SND_ASOC_JZ_EXTCODEC_NPCA110P) += snd-asoc-excodec-npca110p.o
obj-$(CONFIG_SND_ASOC_JZ_EXTCODEC_AKM4951)  += snd-asoc-excodec-akm4951.o

obj-$(CONFIG_SND_ASOC_JZ_PCM_V12) += snd-asoc-pcm-v12.o
obj-$(CONFIG_SND_ASOC_JZ_PCM_V13) += snd-asoc-pcm-v13.o
obj-$(CONFIG_SND_ASOC_JZ_PCM_DUMP_CDC) += snd-asoc-pcm-dump.o

obj-$(CONFIG_SND_ASOC_JZ_SPDIF_V12) += snd-asoc-spdif-v12.o
obj-$(CONFIG_SND_ASOC_JZ_SPDIF_V13) += snd-asoc-spdif-v13.o
obj-$(CONFIG_SND_ASOC_JZ_SPDIF_DUMP_CDC) += snd-asoc-spdif-dump.o

obj-$(CONFIG_SND_ASOC_JZ_DMIC_V13) += snd-asoc-dmic-v13.o
obj-$(CONFIG_SND_ASOC_JZ_DMIC_DUMP_CDC) += snd-asoc-dmic-dump.o

snd-soc-dorado-icdc-objs   := /asoc-board/dorado_icdc.o
snd-soc-mensa-icdc-objs	   := /asoc-board/mensa_icdc.o
snd-soc-mensa-spdif-objs   := /asoc-board/mensa_spdif.o
snd-soc-phoenix-spdif-objs := /asoc-board/phoenix_spdif.o
snd-soc-phoenix-icdc-objs  := /asoc-board/phoenix_icdc.o
snd-soc-canna-spdif-objs := /asoc-board/canna_spdif.o
snd-soc-canna-icdc-objs  := /asoc-board/canna_icdc.o
snd-soc-halley2-spdif-objs := /asoc-board/halley2_spdif.o
snd-soc-halley2-icdc-objs  := /asoc-board/halley2_icdc.o
snd-soc-m1-npca110p-objs  := /asoc-board/m1_npca110p.o
snd-soc-aslmom-akm4951-objs  := /asoc-board/aslmom_akm4951.o
obj-$(CONFIG_SND_ASOC_INGENIC_DORADO_ICDC) += snd-soc-dorado-icdc.o
obj-$(CONFIG_SND_ASOC_INGENIC_MENSA_ICDC) += snd-soc-mensa-icdc.o
obj-$(CONFIG_SND_ASOC_INGENIC_MENSA_SPDIF) += snd-soc-mensa-spdif.o
obj-$(CONFIG_SND_ASOC_INGENIC_PHOENIX_ICDC) += snd-soc-phoenix-icdc.o
obj-$(CONFIG_SND_ASOC_INGENIC_PHOENIX_SPDIF) += snd-soc-phoenix-spdif.o
obj-$(CONFIG_SND_ASOC_INGENIC_CANNA_ICDC) += snd-soc-canna-icdc.o
obj-$(CONFIG_SND_ASOC_INGENIC_CANNA_SPDIF) += snd-soc-canna-spdif.o
obj-$(CONFIG_SND_ASOC_INGENIC_M1_NPCA110P) += snd-soc-m1-npca110p.o
obj-$(CONFIG_SND_ASOC_INGENIC_HALLEY2_ICDC) += snd-soc-halley2-icdc.o
obj-$(CONFIG_SND_ASOC_INGENIC_HALLEY2_SPDIF) += snd-soc-halley2-spdif.o
obj-$(CONFIG_SND_ASOC_INGENIC_ASLMOM_AKM4951) += snd-soc-aslmom-akm4951.o
